name: nova_agenda
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^1.1.0
  intl: ^0.17.0
  supabase: ^0.2.10
  table_calendar: ^3.0.3
  font_awesome_flutter: ^9.2.0
  get: ^4.5.1
  get_storage: ^2.0.3
  toggle_switch: ^1.3.0
  flutter_colorpicker: ^1.0.3
  mask_text_input_formatter: ^2.0.0
  via_cep_flutter: ^0.2.2
  staggered_grid_view_flutter: ^0.0.4
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/imagens/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-MediumItalic.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Black.ttf
        - asset: assets/fonts/RobotoSlab-Bold.ttf
        - asset: assets/fonts/RobotoSlab-ExtraBold.ttf
        - asset: assets/fonts/RobotoSlab-ExtraLight.ttf
        - asset: assets/fonts/RobotoSlab-Light.ttf
        - asset: assets/fonts/RobotoSlab-Medium.ttf
        - asset: assets/fonts/RobotoSlab-Regular.ttf
        - asset: assets/fonts/RobotoSlab-SemiBold.ttf
